### ISSUE TITLE
Column `'zohoable_id'` cannot be null

### ISSUE THREAD

**Issue by ibmgeniuz** [asciisd/zoho#12]
@aemaddin I get Column `'zohoable_id'` cannot be null when I try to use `$leads->createOrUpdateZohoId($id); `. Will there be any reason this is the case? Is that autogenerated or there is a way to set `zohoable_id` for each model. 

Thank you

**Comment by aemaddin** [comment]
please can you send me the code sample for how you use the method, and also the exception trace.

**Comment by ibmgeniuz** [comment]
> please can you send me the code sample for how you use the method, and also the exception trace.

```php
Route::get('zoho/test/modules', function (){
    $leads = new App\Models\ZohoLead();
    $leads->createOrUpdateZohoId('VALID_ID_FROM_ZOHO_HERE');
});
```
Then I visited the link `zoho/test/modules` with postman. That's when I got this error. Where I use tinker, it tells me that there's no table as in [ISSUE](https://github.com/asciisd/zoho/issues/11#issue-785475502) . Postman works better but when the data is being saved, I get this problem.

**Comment by aemaddin** [comment]
createOrUpdate method is used to createOrUpdate CRM record, so you can used it after created a new Laravel model and you need to send it to CRM and save the CRM record id,

so this method can be used with Laravel model, for ex:

```php
$user = App\Models\User::find(1);
$user->createOrUpdateZohoId();
```

if you leave $id empty or null, in this case zohobale will look into zohoable database to find this record and use it's CRM id, in case it's not exists it will try to find the record on Zoho CRM by searchByCriteria, finally if is not exists it will be create a new record on the Zoho CRM, return the new record id and save it on zohoable table.

**Comment by ibmgeniuz** [comment]
The exception I got was this. I think it was rather looking for a value for `zohoable_id` but couldn't find any. Can you please tell me how the code generates that or how I could generate from my model? I try the `creating()` static boot method but because it is not really using the Laravel Model directly, I can not change the data before it is saved. 

```json
{
    "message": "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'zohoable_id' cannot be null (SQL: insert into `zohos` (`zoho_id`, `zohoable_id`, `zohoable_type`, `updated_at`, `created_at`) values (REPLACE_WITH_VALID_ID_FROM_ZOHO_HERE, ?, App\\Models\\ZohoLead, 2021-01-14 12:59:57, 2021-01-14 12:59:57))",
    "exception": "Illuminate\\Database\\QueryException",
```

**Comment by aemaddin** [comment]
try this
https://github.com/asciisd/zoho/issues/11#issuecomment-760249703

**Comment by aemaddin** [comment]
also you need to fill searchByCriteria method to get the record from CRM in case of updating or search if it's exists.

finally you need to fill zohoMandatoryFields method because it's the map method that will used when you create a new record into Zoho CRM

**Comment by ibmgeniuz** [comment]
> try this
> [#11 (comment)](https://github.com/asciisd/zoho/issues/11#issuecomment-760249703)

I already changed it by this recommendation but still I get the 

> The exception I got was this. I think it was rather looking for a value for `zohoable_id` but couldn't find any. Can you please tell me how the code generates that or how I could generate from my model? I try the `creating()` static boot method but because it is not really using the Laravel Model directly, I can not change the data before it is saved.
> 
> ```json
> {
>     "message": "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'zohoable_id' cannot be null (SQL: insert into `zohos` (`zoho_id`, `zohoable_id`, `zohoable_type`, `updated_at`, `created_at`) values (REPLACE_WITH_VALID_ID_FROM_ZOHO_HERE, ?, App\\Models\\ZohoLead, 2021-01-14 12:59:57, 2021-01-14 12:59:57))",
>     "exception": "Illuminate\\Database\\QueryException",
> ```

I know I can try to update the migration for `zohos` table to make zohoable_id nullable which could make the code work, but I don't know how that will affect other parts of the package. I'm trying not to hack my way through. 
Can that  cause any issues?

**This is my current code:**

```php
<?php

namespace Modules\Zoho\Models\Api;

use Asciisd\Zoho\CriteriaBuilder;
use Asciisd\Zoho\Zohoable;

class Lead extends Zohoable
{
    protected $zoho_module_name = 'Leads';

    public function searchCriteria()
    {
        // TODO: Implement searchCriteria() method.
    }

    public function zohoMandatoryFields()
    {
        // TODO: Implement zohoMandatoryFields() method.
    }
}
```

**Comment by ibmgeniuz** [comment]
My currency code has 
```php
class Lead extends Zohoable
{
    protected $zoho_module_name = 'Leads';

    public function searchCriteria()
    {
        return CriteriaBuilder::where('Email', $this->Email)
            ->toString();
    }

    public function zohoMandatoryFields()
    {
        return ['Email' => $this->Email];
    }
```

@aemaddin I think that the problem is with saving to the Local Database and not to Zoho CRM

**Comment by aemaddin** [comment]
ok I am trying to replicate your example and will get back to you.

**Comment by aemaddin** [comment]
@ibmgeniuz 
as you can see here:-
<img width="1440" alt="Screen Shot 2021-01-14 at 7 50 13 PM" src="https://user-images.githubusercontent.com/11630742/104629176-d0ef5000-56a1-11eb-895f-038709449beb.png">

I can create Zoho instance from my model without any problems,

so can you make sure that your model table is already exists.

Thanks

**Comment by aemaddin** [comment]
yes please if you send PR that will be great

Thanks.

**Comment by ibmgeniuz** [comment]
Hello, @aemaddin I have created a [Pull Request](https://github.com/asciisd/zoho/pull/13#issue-556397473). Please check and let me know if it is okay with you. In case I get to find out more ways people could use this package as I develop, I will add them to the docs. This package is amazing and very well written. 

Thank you.
