### ISSUE TITLE
No Tokens exist for the given user-identifier - zcrm_oathtokens.txt empty

### ISSUE THREAD

**Issue by maximus1127** [asciisd/zoho#14]
Hi, thank you so much for this great package. I am having an issue with setting up. I followed your docs carefully (multiple times) and when I do `php artisan zoho:install` I do not get a config file in the config folder. So I copied the default one from your repo. But even after I authorize and copy/paste the URL, my token and log files are empty and I don't know what to do to get them filled with data so I can use the rest of the package. I get the error of "no tokens exist". I noticed that before, there were other issues related to this and they were resolved. From what I can see, all fixes in those issues are present on my installation. I'm on laravel 7.0 and cannot get this to work for the life of me. Is there any advice you can offer?

**Comment by aemaddin** [comment]
Hi Maximus,

This error mean that your zoho email account is not set correctly on .env file or maybe you don't have permission to use API.
