### ISSUE TITLE
Redirect URL problem

### ISSUE THREAD

**Issue by hungtruongquoc** [asciisd/zoho#15]
Should we read the URL from the configuration file?

https://github.com/asciisd/zoho/blob/7d65824e02f145dc14e9427b516226ec5f7dc5c8/src/Console/Commands/ZohoAuthentication.php#L43

**Comment by aemaddin** [comment]
Hi Hung Truong,

This url auto generated from your current project settings, so this line will add the application url as you set it inside .env file (APP_URL=https://your-web-site.com), so if you need to change it for any reason you can change it from .env file not from settings.

after that you can just generate the auth from artisan command like. that
```bash
php artisan Zoho:authentication
```
I hope that will help you

Thanks.
