### ISSUE TITLE
How to return data only

### ISSUE THREAD

**Issue by jayomayan** [asciisd/zoho#21]
$leads = ZohoManager::useModule('Leads')->searchRecordsByCriteria($builder->toString());
How do i return data only on this command?

On this command below, i can get data only.
$lead = $leads->getRecord('4470003000036452043')->getData();

**Comment by aemaddin** [comment]
```php
$leads = ZohoManager::useModule('Leads')->searchRecordsByCriteria("(City:equals:Los Angeles) and (State:equals: California)");
```

**Comment by jayomayan** [comment]
Thanks
