### ISSUE TITLE
Possible to retrieve options from select field in CRM?

### ISSUE THREAD

**Issue by jk-1001** [asciisd/zoho#25]
Hi there,

The package is really great so thanks for that. However, I have a quick question.

If a select field is setup in the CRM, is it possible to pull the options from there through this package? So that the CRM and the web form would remain in sync? Or do I need to manually enter this information?
I could not see anything about this in the how to use code so maybe it isn't possible but a confirmation would be appreciated. Thanks!

**Comment by aemaddin** [comment]
Hi JK,

Thanks for contributing, but this feature is not introduced by this package, but you're very welcomed to contribute if you want.
