### ISSUE TITLE
Token expire in hour

### ISSUE THREAD

**Issue by sanketr43** [asciisd/zoho#29]
I have done setup in laravel for this. But I have to do authentication every day. how to persist the token in this. so after once i never have to generate manaully?

**Comment by aemaddin** [comment]
(configuration section)[https://github.com/asciisd/zoho#configuration]

actually, you don't have to re-authenticate every time, follow the config instruction will create a new file inside the storage directory to hold the token and reuse it.

**Comment by aemaddin** [comment]
Also please make sure that the file holds both token and refresh token, the refresh token is responsible for renewing the token after expire.

**Comment by sanketr43** [comment]
I have done the same configuration as mentioned in the document. But still it won't works.

**Comment by sanketr43** [comment]
Yes this all details are available. but still when i call zoho create/update module details next day. it doesn't work unless i do the authentication.

**Comment by sanketr43** [comment]
can anyone help?

**Comment by danielfaulknor** [comment]
@AliMehraei check out my comment on #42
