### ISSUE TITLE
Related Lists

### ISSUE THREAD

**Issue by chadleverington** [asciisd/zoho#30]
Hey guys, thanks for this package, ive got all the examples working just wondering how i would use the "Related Lists" REST 2.1 api. 

For example i have an account with the id 3220021000035501093 and i want to get the notes related to that account i would call 
http://www.zohoapis.com/crm/2.1/Accounts/3220021000035501093/Notes

and this returns the json in postman, but how do i make that url call using this package?

thanks

**Comment by aemaddin** [comment]
Hi @chadleverington ,

Yes you can get the related list by calling for example

```php
$lead_record->getRelatedListRecords('Notes')
```
