### ISSUE TITLE
Workflows does not triggered

### ISSUE THREAD

**Issue by wmfairuz** [asciisd/zoho#32]
Hi,

Thanks for the package! I have one question regarding workflows that has been setup when a lead is created.

Is it possible to also trigger workflows when creating record using this package? Thanks!

**Comment by aemaddin** [comment]
Thaks for your contribution, 

just update to the latest version and you will be able to pass workflows as a string with comma separated

```php
$lead->update($trigger);
// OR
$lead->create($trigger);
// OR
$lead->insert($record, $trigger)
```
