### ISSUE TITLE
`$this->response` is `false` in CommonAPIResponse class

### ISSUE THREAD

**Issue by bfiessinger** [asciisd/zoho#35]
Whenever I try to call the Zoho API via this package I get an `Undefined array key 1` error from CommonAPIResponse.php (zohocrm/php-sdk-archive) due to a false value in the response.

Reading `$this` in the `setResponseJSON` method shows me many undefined vars

```php
zcrmsdk\crm\api\response\BulkAPIResponse {[#2233 ▼]()
  -bulkData: null
  -status: null
  -info: null
  -bulkEntitiesResponse: null
  -httpStatusCode: 0
  -responseJSON: null
  -responseHeaders: null
  -code: null
  -message: null
  -details: null
  -response: false
  -apiName: null
}
```

I am currently running on localhost. Tried to setup on an environment with pretty URL and via php artisan serve. Both times authentication worked but the responses are the same no matter if I want to read or manipulate data.

**Comment by sarojasp** [comment]
same problem

**Comment by sarojasp** [comment]
Hi, hi resolved this problem changed the Curl certificate. You can see the solution In [https://www.zoho.com/crm/developer/docs/php-sdk/errors-solutions.html](url)
