### ISSUE TITLE
Missing /storage/app/zoho/oauth/logs/ZCRMClientLibrary.log

### ISSUE THREAD

**Issue by brentstrandy** [asciisd/zoho#36]
I'm getting an error whenever I attempt to use this package. Basically, asciisd/zoho is looking for a log file inside my container's file structure. This feels odd as other frameworks will create the files they need.

Does this happen for everyone? What are you doing to get around this error? I don't want to add "create the file ZCRMClientLibrary.log" to my build process - that feels like an anti-pattern. Thanks!

Here's the error message I'm seeing:
fopen(/var/www/myapp/storage/app/zoho/oauth/logs/ZCRMClientLibrary.log): failed to open stream: No such file or directory

**Comment by aemaddin** [comment]
Hi @brentstrandy,

You can use the artisan command for that.

```bash
php artisan zoho:install
```
this command will generate two files for you inside the project storage directory,

unfortunately, this is not my package error. Zoho's php package requires creating a log file and sending the file path on initialization, but let me try to pass the Laravel log file path and see what will happen

Thanks for your contribution
