### ISSUE TITLE
Getting File from ZFS

### ISSUE THREAD

**Issue by chanz-kiyo** [asciisd/zoho#38]
Is there a way to get the files from an API that is Image Upload type?

For reference [https://www.zoho.com/crm/developer/docs/api/get-files.html](url)

**Comment by aemaddin** [comment]
try to use 
```php
$record->getAttachments($params)
```

**Comment by chanz-kiyo** [comment]
New question. Will the package be upgraded to API ver 2.1?

**Comment by aemaddin** [comment]
Hello Chanz,

Actually, the package using API v2.2

<img width="316" alt="Screen Shot 2022-03-25 at 11 40 17 AM" src="https://user-images.githubusercontent.com/11630742/160095914-4d973bf1-0bab-4e45-a98f-c95d22e676ac.png">
