### ISSUE TITLE
get more than 200 records using getRecords()

### ISSUE THREAD

**Issue by wmfairuz** [asciisd/zoho#43]
Hi,

I'm trying to retrieve all my modules data using:

`$data = ZohoManager::useModule($module_name)->getRecords()`

But I only get the first 200 of the entries, is it possible to specify page and perpage values for getRecords()? 

Thanks!

**Comment by aemaddin** [comment]
Hi @wmfairuz,

Package updated on v2 with new feature as you requested.

Thanks for your contribution.
