### ISSUE TITLE
Type of zcrmsdk\oauth\exception\ZohoOAuthException::$file must be string (as in class Exception)

### ISSUE THREAD

**Issue by imadys** [asciisd/zoho#44]
Can you tell me what is this error?
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/47067573/190140367-487a1483-8dae-4582-979c-4fbfaec36b70.png">

**Comment by rogerio-pereira** [comment]
https://github.com/asciisd/zoho/issues/42

**Comment by imadys** [comment]
Thanks!

**Comment by rogerio-pereira** [comment]
@aemaddin Feedback about v.2.0.3
For me this updated worked as a charm
tested Scenarios:

- convert lead
- create sales orders
- update sales orders
- create task
- Create products
- Update Products
- update lead
- create account

**Comment by aemaddin** [comment]
@rogerio-pereira Thanks for testing. You can also upgrade to the new package V3 from here: 

https://github.com/asciisd/zoho-v3
