### ISSUE TITLE
Dealing with invalid_redirect_uri

### ISSUE THREAD

**Issue by kbellpostman** [asciisd/zoho#45]
Good morning,

It took me while to figure out ZOHO_REDIRECT_URI is supposed to hold my own domains redirect url, not Zoho's. I ended up going through all the code of the projects code to find out. Maybe it could help people to clarify a little bit extra this in the readme. 

![image](https://user-images.githubusercontent.com/60920059/190359706-c4e65eff-6577-4b02-bd4a-a5f9f14fcc0c.png)

**Comment by aemaddin** [comment]
Hi @kbellpostman,

Sorry for that. Updated documentation to make it easier for new developers.

Thanks for your contribution.
