### ISSUE TITLE
Guzzle 7

### ISSUE THREAD

**Issue by Sourcefli** [asciisd/zoho#5]
Any plan to update to guzzle 7? 

Not allowing installation in a new Laravel 8 installation. 

Error is:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - asciisd/zoho v1.1.0 requires guzzlehttp/guzzle ^6.5 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for asciisd/zoho ^1.1 -> satisfiable by asciisd/zoho[v1.1.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].

**Comment by asciisd** [comment]
Dear,

Sorry for inconvenience, you can now use this package on Laravel 8, have a nice day.

**Comment by asciisd** [comment]
Do you have any problems with new release? I will close the issue after one week if there is no response from you

Thanks for using the package.

**Comment by Sourcefli** [comment]
sorry for delayed response. 

I will give this a shot now and get back to you asap.

thanks for the update

**Comment by Sourcefli** [comment]
Working great, thank you!
