### ISSUE TITLE
Not able to configure on localhost/virtualHost

### ISSUE THREAD

**Issue by akhil-aecor** [asciisd/zoho#9]
Hi, can you please provide the steps how to configure this plugin on localhost/virtualhost, and how to skip https issue as well.

**Comment by aemaddin** [comment]
Hi Akhil,

There is no special configuration to use this library on virtual host or localhost, you can use it like any other plugin,

### 1 - install package into your Laravel project
```bash
composer require asciisd/zoho
```

### 2 - add Zoho OAuth and Log folders into your storage by run this command
```bash
php artisan zoho:install
```

### 3 - after that you need to [create new client](https://accounts.zoho.com/developerconsole) to continue.
- ADD CLIENT `Server-based Applications`.
- Enter Client Name `Any name you want`
- Enter Homepage URL `your base home url`
- Enter Authorized Redirect URIs `http://your-base-url/zoho/oauth2callback`

### 4 - add .env variables from generated client
```patch
ZOHO_CLIENT_ID=
ZOHO_CLIENT_SECRET=
ZOHO_REDIRECT_URI=
ZOHO_CURRENT_USER_EMAIL=
```
### 5 - generate auth link by run this command and press on the link generated to start Oauth process
```bash
php artisan zoho:authentication
```

### finally:-
you will prompted to allow authorization to access your Zoho account from your project, and you will be redirected after successfully auth you your home page with message `Zoho CRM has been set up successfully.`

**Comment by aemaddin** [comment]
for https issue I don't know what you mean, can you please send me more details about this issue to be able to help.

Thanks for using the package

**Comment by aemaddin** [comment]
Hi @akhil-aecor 

is that issue solved yet?

**Comment by aemaddin** [comment]
closed since there is no response, so it seems to be solved.
